---
- name: playing with facts
  hosts: localhost
  gather_facts: true

  tasks:
  - debug:
      msg: 
        - " Data type of 'ansible_hostname'  is {{ ansible_hostname | type_debug }} "
        - " Data type of 'ansible_selinux' is {{ ansible_selinux | type_debug }} "
        - " Data type of 'ansible_all_ipv4_addresses' is {{ ansible_all_ipv4_addresses | type_debug }} "
  - debug:
      msg: "{{ ansible_all_ipv4_addresses }}"
  - debug:
      msg: "{{ ansible_all_ipv4_addresses[0] }}"
