---
- name: playing with debug
  hosts: localhost

  gather_facts: false

  tasks:
  - name: command
    shell: echo Hello world
    register: output

  - name: debug with var
    debug:
      var: output

  - name: debug with msg
    debug:
      msg: this is the stdout of the command {{ output.stdout_lines }}
