---
- name: playing with tags
  hosts: localhost

  gather_facts: false

  tasks:
  - name: red
    command: echo Hello Red
    tags:
      - red

  - name: hat
    command: echo Hello Hat
    tags:
      - hat

  - name: red hat
    command: echo Hello Red Hat
    tags:
      - red
      - hat
